#ifndef __SHIMS
#define __SHIMS

#include <stdint.h>

typedef uint8_t DuelBool;

typedef struct {
    int16_t CardID; // 0x0
    int16_t EffectID; // 0x2
    int32_t Atk; // 0x4
    int32_t Def; // 0x8
    int32_t OrgAtk; // 0xC
    int32_t OrgDef; // 0x10
    int16_t Type; // 0x14
    int16_t Attr; // 0x16
    int16_t Element; // 0x18
    int16_t Level; // 0x1A
    int8_t Rank; // 0x1C
    int8_t VoidMagic; // 0x1D
    int8_t VoidTrap; // 0x1E
    int8_t VoidMonst; // 0x1F
} DuelBasicVal;

typedef uint32_t (*DuelThreadRunEffectDeleg)(uint32_t id, uint32_t param1, uint32_t param2, uint32_t param3);
typedef uint32_t (*DuelThreadIsBusyEffectDeleg)(uint32_t id);
typedef void (*DuelAddRecord)(uint32_t* ptr, uint32_t size);
typedef uint32_t* (*DuelNowRecord)(void);
typedef void (*DuelRecordNext)(void);
typedef void (*DuelRecordBegin)(void);
typedef uint32_t (*DuelIsRecordEnd)(void);

int32_t SetCardPropertyShim(int8_t* data, int32_t size);
void SetInternalIDShim(int8_t* data);
void SetCardSameShim(int8_t* data, int32_t size);
void SetCardNamedShim(int8_t* data);
void SetCardLinkShim(int8_t* data, int32_t size);
void SetCardGenreShim(int8_t* data);
int32_t CardGetInternalIDShim(int32_t cardId);
int32_t CardGetTypeShim(int32_t cardId);
int32_t CardGetAttrShim(int32_t cardId);
int32_t CardGetStarShim(int32_t cardId);
int32_t CardGetLevelShim(int32_t cardId);
int32_t CardGetRankShim(int32_t cardId);
int32_t CardGetScaleLShim(int32_t cardId);
int32_t CardGetScaleRShim(int32_t cardId);
int32_t CardGetLinkNumShim(int32_t cardId);
int32_t CardGetLinkMaskShim(int32_t cardId);
int32_t CardGetIconShim(int32_t cardId);
int32_t CardGetFrameShim(int32_t cardId);
int32_t CardGetKindShim(int32_t cardId);
int32_t CardGetAtkShim(int32_t cardId);
int32_t CardGetDefShim(int32_t cardId);
int32_t CardGetAtk2Shim(int32_t cardId);
int32_t CardGetDef2Shim(int32_t cardId);
int32_t CardGetLimitationShim(int32_t cardId);
int32_t CardIsThisCardGenreShim(int32_t cardId, int32_t genreId);
int32_t CardIsThisSameCardShim(int32_t cardA, int32_t cardB);
int32_t CardGetOriginalIDShim(int32_t cardId);
int32_t CardGetOriginalID2Shim(int32_t cardId);
int32_t CardGetAlterIDShim(int32_t cardId);
int32_t CardGetAltCardIDShim(int32_t cardId, int32_t alterID);
int32_t CardCheckNameShim(int32_t cardId, int32_t nameType);
int32_t CardGetLinkCardsShim(int32_t cardId, void* pLinkID);
int32_t CardGetBasicValShim(int32_t cardId, DuelBasicVal* pVal);
int32_t CardIsThisTunerMonsterShim(int32_t cardId);
int32_t DuelDlgGetMixNumShim();
int32_t DuelDlgGetMixTypeShim(int32_t index);
int32_t DuelDlgGetMixDataShim(int32_t index);
void DuelDlgSetResultShim(uint32_t result);
int32_t DuelDlgCanYesNoSkipShim();
int32_t DuelDlgGetPosMaskOfThisSummonShim();
int32_t DuelDlgGetSelectItemNumShim();
int32_t DuelDlgGetSelectItemStrShim(int32_t index);
int32_t DuelDlgGetSelectItemEnableShim(int32_t index);
int32_t DlgProcGetSummoningMonsterUniqueIDShim();
int32_t GetRevisionShim();
int32_t GetBinHashShim(int32_t iIndex);
int32_t SetWorkMemoryShim(void* pWork);
int32_t DuelSysInitRushShim();
int32_t DuelSysInitQuestionShim(void* pScript);
int32_t DuelSysInitCustomShim(int32_t fDuelType, DuelBool tag, int32_t life0, int32_t life1, int32_t hand0, int32_t hand1, DuelBool shuf);
int32_t DuelSysActShim();
void DuelSysClearWorkShim();
void DuelSysSetDeck2Shim(int32_t player, int* mainDeck, int32_t mainNum, int* extraDeck, int32_t extraNum, int* sideDeck, int32_t sideNum);
void DuelSetRandomSeedShim(uint32_t seed);
void DuelSetMyPlayerNumShim(int32_t player);
void DuelSetPlayerTypeShim(int32_t player, int32_t type);
int32_t DuelIsHumanShim(int32_t player);
int32_t DuelMyselfShim();
int32_t DuelRivalShim();
int32_t DuelIsMyselfShim(int32_t player);
int32_t DuelIsRivalShim(int32_t player);
void DuelSetCpuParamShim(int32_t player, uint32_t param);
void DuelSetFirstPlayerShim(int32_t player);
int32_t DuelGetDuelResultShim();
int32_t DuelGetDuelFinishShim();
int32_t DuelGetDuelFinishCardIDShim();
void DuelSetDuelLimitedTypeShim(uint32_t limitedType);
void SetEffectDelegateShim(DuelThreadRunEffectDeleg runEffct, DuelThreadIsBusyEffectDeleg isBusyEffect);
int32_t DuelIsThisQuickDuelShim();
void SetCardExistWorkShim(void* pWork, int32_t size, int32_t count);
int32_t GetCardExistNumShim();
int32_t DuelGetLPShim(int32_t player);
int32_t DuelWhichTurnNowShim();
uint32_t DuelGetCurrentPhaseShim();
uint32_t DuelGetCurrentStepShim();
uint32_t DuelGetCurrentDmgStepShim();
uint32_t DuelGetTurnNumShim();
void* DuelGetCardPropByUniqueIDShim(int32_t uniqueId);
int32_t DuelGetCardUniqueIDShim(int32_t player, int32_t position, int32_t index);
int32_t DuelGetCardTurnShim(int32_t player, int32_t position, int32_t index);
int32_t DuelGetCardFaceShim(int32_t player, int32_t position, int32_t index);
int32_t DuelGetCardNumShim(int32_t player, int32_t locate);
int32_t DuelGetTopCardIndexShim(int32_t player, int32_t locate);
DuelBool DuelGetHandCardOpenShim(int32_t player, int32_t index);
uint32_t DuelSearchCardByUniqueIDShim(int32_t uniqueId);
uint32_t DuelGetCardIDByUniqueID2Shim(int32_t uniqueId);
uint32_t DuelCanIDoPutMonsterShim(int32_t player);
DuelBool DuelCanIDoSummonMonsterShim(int32_t player);
DuelBool DuelCanIDoSpecialSummonShim(int32_t player);
uint32_t DuelGetCardInHandShim(int32_t player);
void DuelGetCardBasicValShim(int32_t player, int32_t pos, int32_t index, DuelBasicVal* pVal);
int32_t DuelGetTrapMonstBasicValShim(int32_t cardId, DuelBasicVal* pVal);
int32_t DuelGetThisCardOverlayNumShim(int32_t player, int32_t locate);
int32_t FusionGetMaterialListShim(int32_t uniqueId, void* list);
int32_t FusionIsThisTunedMonsterInTuningShim(int32_t wUniqueID);
int32_t FusionGetMonsterLevelInTuningShim(int32_t wUniqueID);
int32_t DuelIsThisCardExistShim(int32_t player, int32_t locate);
int32_t DuelGetThisCardEffectIDAtChainShim(int32_t player, int32_t locate);
int32_t DuelGetAttackTargetMaskShim(int32_t player, int32_t locate);
int32_t DuelGetThisCardDirectFlagShim(int32_t player, int32_t index);
void DuelGetFldAffectIconShim(int32_t player, int32_t locate, void* ptr, int32_t view_player);
int32_t DuelGetThisCardCounterShim(int32_t player, int32_t locate, int32_t counter);
int32_t DuelGetThisCardTurnCounterShim(int32_t player, int32_t locate);
int32_t DuelIsThisTunerMonsterShim(int32_t player, int32_t locate);
int32_t DuelIsThisNormalMonsterShim(int32_t player, int32_t locate);
DuelBool DuelIsThisEffectiveMonsterShim(int32_t player, int32_t index);
DuelBool DeulIsThisEffectiveMonsterWithDualShim(int32_t player, int32_t index);
DuelBool DuelIsThisNormalMonsterInGraveShim(int32_t player, int32_t index);
DuelBool DuelIsThisNormalMonsterInHandShim(int32_t wCardID);
int32_t DuelIsThisTrapMonsterShim(int32_t player, int32_t locate);
int32_t DuelGetThisCardEffectFlagsShim(int32_t player, int32_t locate);
int32_t DuelGetFldMonstOrgLevelShim(int32_t player, int32_t locate);
int32_t DuelGetFldMonstOrgTypeShim(int32_t player, int32_t locate);
int32_t DuelGetFldPendScaleShim(int32_t player, int32_t locate);
int32_t DuelGetFldPendOrgScaleShim(int32_t player, int32_t locate);
int32_t DuelGetFldMonstRankShim(int32_t player, int32_t locate);
int32_t DuelGetFldMonstOrgRankShim(int32_t player, int32_t locate);
int32_t DuelIsThisZoneAvailableShim(int32_t player, int32_t locate);
int32_t DuelIsThisZoneAvailable2Shim(int32_t player, int32_t locate, DuelBool visibleOnly);
int32_t DuelGetThisCardShowParameterShim(int32_t player, int32_t locate);
uint32_t DuelGetThisCardParameterShim(int32_t player, int32_t locate);
uint32_t DuelGetThisCardEffectListShim(int32_t player, int32_t locate, void* list);
uint32_t DUELCOMGetPosMaskOfThisHandShim(int32_t player, int32_t index, int32_t commandId);
int32_t DuelIsThisContinuousCardShim(int32_t player, int32_t locate);
int32_t DuelIsThisEquipCardShim(int32_t player, int32_t locate);
DuelBool DuelIsThisMagicShim(int32_t player, int32_t locate);
DuelBool DuelIsThisTrapShim(int32_t player, int32_t locate);
DuelBool DuelGetThisMonsterFightableOnEffectShim(int32_t player, int32_t locate);
int32_t DUELCOMGetRecommendSideShim();
DuelBool DuelGetDuelFlagDeckReverseShim();
uint32_t DuelComGetCommandMaskShim(int32_t player, int32_t position, int32_t index);
uint32_t DuelComGetTextIDOfThisCommandShim(int32_t player, int32_t position, int32_t index);
uint32_t DuelComGetTextIDOfThisSummonShim(int32_t player, int32_t position, int32_t index);
void DuelComDoCommandShim(int32_t player, int32_t position, int32_t index, int32_t commandId);
int32_t DuelComCancelCommand2Shim(DuelBool decide);
void DuelComDefaultLocationShim();
uint32_t DuelComGetMovablePhaseShim();
void DuelComMovePhaseShim(int32_t phase);
void DuelComDebugCommandShim();
uint32_t CardRareGetBufferSizeShim();
void CardRareSetRareShim(void* pBuf, void* rare0, void* rare1, void* rare2, void* rare3);
int32_t CardRareGetRareByUniqueIDShim(int32_t uniqueId);
void CardRareSetBufferShim(void* pBuf);
int32_t DuelResultGetMemoShim(int32_t player, void* dst);
int32_t DuelResultGetDataShim(int32_t player, void* dst);
void SetAddRecordDelegateShim(DuelAddRecord addRecord);
void SetPlayRecordDelegateShim(DuelNowRecord nowRecord, DuelRecordNext recordNext, DuelRecordBegin recordBegin, DuelIsRecordEnd isRecordEnd);
int32_t DuelIsReplayModeShim();
void SetDuelChallengeShim(int32_t flagbit);
void SetDuelChallenge2Shim(int32_t player, int32_t flagbit);
int32_t DuelListIsMultiModeShim();
void DuelListInitStringShim();
int32_t DuelListGetSelectMaxShim();
int32_t DuelListGetSelectMinShim();
int32_t DuelListGetItemMaxShim();
int32_t DuelListGetItemIDShim(int32_t index);
int32_t DuelListGetItemUniqueIDShim(int32_t index);
int32_t DuelListGetItemFromShim(int32_t index);
int32_t DuelListGetItemMsgShim(int32_t index);
int32_t DuelListGetItemAttributeShim(int32_t index);
int32_t DuelListGetCardAttributeShim(int32_t iLookPlayer, int32_t wUniqueID);
void DuelListSetIndexShim(int32_t index);
void DuelListSetCardExDataShim(int32_t index, int32_t data);
int32_t DuelListGetItemTargetUniqueIDShim(int32_t index);

typedef int32_t (*SetCardPropertyType)(int8_t* data, int32_t size);
typedef void (*SetInternalIDType)(int8_t* data);
typedef void (*SetCardSameType)(int8_t* data, int32_t size);
typedef void (*SetCardNamedType)(int8_t* data);
typedef void (*SetCardLinkType)(int8_t* data, int32_t size);
typedef void (*SetCardGenreType)(int8_t* data);
typedef int32_t (*CardGetInternalIDType)(int32_t cardId);
typedef int32_t (*CardGetTypeType)(int32_t cardId);
typedef int32_t (*CardGetAttrType)(int32_t cardId);
typedef int32_t (*CardGetStarType)(int32_t cardId);
typedef int32_t (*CardGetLevelType)(int32_t cardId);
typedef int32_t (*CardGetRankType)(int32_t cardId);
typedef int32_t (*CardGetScaleLType)(int32_t cardId);
typedef int32_t (*CardGetScaleRType)(int32_t cardId);
typedef int32_t (*CardGetLinkNumType)(int32_t cardId);
typedef int32_t (*CardGetLinkMaskType)(int32_t cardId);
typedef int32_t (*CardGetIconType)(int32_t cardId);
typedef int32_t (*CardGetFrameType)(int32_t cardId);
typedef int32_t (*CardGetKindType)(int32_t cardId);
typedef int32_t (*CardGetAtkType)(int32_t cardId);
typedef int32_t (*CardGetDefType)(int32_t cardId);
typedef int32_t (*CardGetAtk2Type)(int32_t cardId);
typedef int32_t (*CardGetDef2Type)(int32_t cardId);
typedef int32_t (*CardGetLimitationType)(int32_t cardId);
typedef int32_t (*CardIsThisCardGenreType)(int32_t cardId, int32_t genreId);
typedef int32_t (*CardIsThisSameCardType)(int32_t cardA, int32_t cardB);
typedef int32_t (*CardGetOriginalIDType)(int32_t cardId);
typedef int32_t (*CardGetOriginalID2Type)(int32_t cardId);
typedef int32_t (*CardGetAlterIDType)(int32_t cardId);
typedef int32_t (*CardGetAltCardIDType)(int32_t cardId, int32_t alterID);
typedef int32_t (*CardCheckNameType)(int32_t cardId, int32_t nameType);
typedef int32_t (*CardGetLinkCardsType)(int32_t cardId, void* pLinkID);
typedef int32_t (*CardGetBasicValType)(int32_t cardId, DuelBasicVal* pVal);
typedef int32_t (*CardIsThisTunerMonsterType)(int32_t cardId);
typedef int32_t (*DuelDlgGetMixNumType)(void);
typedef int32_t (*DuelDlgGetMixTypeType)(int32_t index);
typedef int32_t (*DuelDlgGetMixDataType)(int32_t index);
typedef void (*DuelDlgSetResultType)(uint32_t result);
typedef int32_t (*DuelDlgCanYesNoSkipType)(void);
typedef int32_t (*DuelDlgGetPosMaskOfThisSummonType)(void);
typedef int32_t (*DuelDlgGetSelectItemNumType)(void);
typedef int32_t (*DuelDlgGetSelectItemStrType)(int32_t index);
typedef int32_t (*DuelDlgGetSelectItemEnableType)(int32_t index);
typedef int32_t (*DlgProcGetSummoningMonsterUniqueIDType)(void);
typedef int32_t (*GetRevisionType)(void);
typedef int32_t (*GetBinHashType)(int32_t iIndex);
typedef int32_t (*SetWorkMemoryType)(void* pWork);
typedef int32_t (*DuelSysInitRushType)(void);
typedef int32_t (*DuelSysInitQuestionType)(void* pScript);
typedef int32_t (*DuelSysInitCustomType)(int32_t fDuelType, DuelBool tag, int32_t life0, int32_t life1, int32_t hand0, int32_t hand1, DuelBool shuf);
typedef int32_t (*DuelSysActType)(void);
typedef void (*DuelSysClearWorkType)(void);
typedef void (*DuelSysSetDeck2Type)(int32_t player, int* mainDeck, int32_t mainNum, int* extraDeck, int32_t extraNum, int* sideDeck, int32_t sideNum);
typedef void (*DuelSetRandomSeedType)(uint32_t seed);
typedef void (*DuelSetMyPlayerNumType)(int32_t player);
typedef void (*DuelSetPlayerTypeType)(int32_t player, int32_t type);
typedef int32_t (*DuelIsHumanType)(int32_t player);
typedef int32_t (*DuelMyselfType)(void);
typedef int32_t (*DuelRivalType)(void);
typedef int32_t (*DuelIsMyselfType)(int32_t player);
typedef int32_t (*DuelIsRivalType)(int32_t player);
typedef void (*DuelSetCpuParamType)(int32_t player, uint32_t param);
typedef void (*DuelSetFirstPlayerType)(int32_t player);
typedef int32_t (*DuelGetDuelResultType)(void);
typedef int32_t (*DuelGetDuelFinishType)(void);
typedef int32_t (*DuelGetDuelFinishCardIDType)(void);
typedef void (*DuelSetDuelLimitedTypeType)(uint32_t limitedType);
typedef void (*SetEffectDelegateType)(DuelThreadRunEffectDeleg runEffct, DuelThreadIsBusyEffectDeleg isBusyEffect);
typedef int32_t (*DuelIsThisQuickDuelType)(void);
typedef void (*SetCardExistWorkType)(void* pWork, int32_t size, int32_t count);
typedef int32_t (*GetCardExistNumType)(void);
typedef int32_t (*DuelGetLPType)(int32_t player);
typedef int32_t (*DuelWhichTurnNowType)(void);
typedef uint32_t (*DuelGetCurrentPhaseType)(void);
typedef uint32_t (*DuelGetCurrentStepType)(void);
typedef uint32_t (*DuelGetCurrentDmgStepType)(void);
typedef uint32_t (*DuelGetTurnNumType)(void);
typedef void* (*DuelGetCardPropByUniqueIDType)(int32_t uniqueId);
typedef int32_t (*DuelGetCardUniqueIDType)(int32_t player, int32_t position, int32_t index);
typedef int32_t (*DuelGetCardTurnType)(int32_t player, int32_t position, int32_t index);
typedef int32_t (*DuelGetCardFaceType)(int32_t player, int32_t position, int32_t index);
typedef int32_t (*DuelGetCardNumType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetTopCardIndexType)(int32_t player, int32_t locate);
typedef DuelBool (*DuelGetHandCardOpenType)(int32_t player, int32_t index);
typedef uint32_t (*DuelSearchCardByUniqueIDType)(int32_t uniqueId);
typedef uint32_t (*DuelGetCardIDByUniqueID2Type)(int32_t uniqueId);
typedef uint32_t (*DuelCanIDoPutMonsterType)(int32_t player);
typedef DuelBool (*DuelCanIDoSummonMonsterType)(int32_t player);
typedef DuelBool (*DuelCanIDoSpecialSummonType)(int32_t player);
typedef uint32_t (*DuelGetCardInHandType)(int32_t player);
typedef void (*DuelGetCardBasicValType)(int32_t player, int32_t pos, int32_t index, DuelBasicVal* pVal);
typedef int32_t (*DuelGetTrapMonstBasicValType)(int32_t cardId, DuelBasicVal* pVal);
typedef int32_t (*DuelGetThisCardOverlayNumType)(int32_t player, int32_t locate);
typedef int32_t (*FusionGetMaterialListType)(int32_t uniqueId, void* list);
typedef int32_t (*FusionIsThisTunedMonsterInTuningType)(int32_t wUniqueID);
typedef int32_t (*FusionGetMonsterLevelInTuningType)(int32_t wUniqueID);
typedef int32_t (*DuelIsThisCardExistType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetThisCardEffectIDAtChainType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetAttackTargetMaskType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetThisCardDirectFlagType)(int32_t player, int32_t index);
typedef void (*DuelGetFldAffectIconType)(int32_t player, int32_t locate, void* ptr, int32_t view_player);
typedef int32_t (*DuelGetThisCardCounterType)(int32_t player, int32_t locate, int32_t counter);
typedef int32_t (*DuelGetThisCardTurnCounterType)(int32_t player, int32_t locate);
typedef int32_t (*DuelIsThisTunerMonsterType)(int32_t player, int32_t locate);
typedef int32_t (*DuelIsThisNormalMonsterType)(int32_t player, int32_t locate);
typedef DuelBool (*DuelIsThisEffectiveMonsterType)(int32_t player, int32_t index);
typedef DuelBool (*DeulIsThisEffectiveMonsterWithDualType)(int32_t player, int32_t index);
typedef DuelBool (*DuelIsThisNormalMonsterInGraveType)(int32_t player, int32_t index);
typedef DuelBool (*DuelIsThisNormalMonsterInHandType)(int32_t wCardID);
typedef int32_t (*DuelIsThisTrapMonsterType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetThisCardEffectFlagsType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldMonstOrgLevelType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldMonstOrgTypeType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldPendScaleType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldPendOrgScaleType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldMonstRankType)(int32_t player, int32_t locate);
typedef int32_t (*DuelGetFldMonstOrgRankType)(int32_t player, int32_t locate);
typedef int32_t (*DuelIsThisZoneAvailableType)(int32_t player, int32_t locate);
typedef int32_t (*DuelIsThisZoneAvailable2Type)(int32_t player, int32_t locate, DuelBool visibleOnly);
typedef int32_t (*DuelGetThisCardShowParameterType)(int32_t player, int32_t locate);
typedef uint32_t (*DuelGetThisCardParameterType)(int32_t player, int32_t locate);
typedef uint32_t (*DuelGetThisCardEffectListType)(int32_t player, int32_t locate, void* list);
typedef uint32_t (*DUELCOMGetPosMaskOfThisHandType)(int32_t player, int32_t index, int32_t commandId);
typedef int32_t (*DuelIsThisContinuousCardType)(int32_t player, int32_t locate);
typedef int32_t (*DuelIsThisEquipCardType)(int32_t player, int32_t locate);
typedef DuelBool (*DuelIsThisMagicType)(int32_t player, int32_t locate);
typedef DuelBool (*DuelIsThisTrapType)(int32_t player, int32_t locate);
typedef DuelBool (*DuelGetThisMonsterFightableOnEffectType)(int32_t player, int32_t locate);
typedef int32_t (*DUELCOMGetRecommendSideType)(void);
typedef DuelBool (*DuelGetDuelFlagDeckReverseType)(void);
typedef uint32_t (*DuelComGetCommandMaskType)(int32_t player, int32_t position, int32_t index);
typedef uint32_t (*DuelComGetTextIDOfThisCommandType)(int32_t player, int32_t position, int32_t index);
typedef uint32_t (*DuelComGetTextIDOfThisSummonType)(int32_t player, int32_t position, int32_t index);
typedef void (*DuelComDoCommandType)(int32_t player, int32_t position, int32_t index, int32_t commandId);
typedef int32_t (*DuelComCancelCommand2Type)(DuelBool decide);
typedef void (*DuelComDefaultLocationType)(void);
typedef uint32_t (*DuelComGetMovablePhaseType)(void);
typedef void (*DuelComMovePhaseType)(int32_t phase);
typedef void (*DuelComDebugCommandType)(void);
typedef uint32_t (*CardRareGetBufferSizeType)(void);
typedef void (*CardRareSetRareType)(void* pBuf, void* rare0, void* rare1, void* rare2, void* rare3);
typedef int32_t (*CardRareGetRareByUniqueIDType)(int32_t uniqueId);
typedef void (*CardRareSetBufferType)(void* pBuf);
typedef int32_t (*DuelResultGetMemoType)(int32_t player, void* dst);
typedef int32_t (*DuelResultGetDataType)(int32_t player, void* dst);
typedef void (*SetAddRecordDelegateType)(DuelAddRecord addRecord);
typedef void (*SetPlayRecordDelegateType)(DuelNowRecord nowRecord, DuelRecordNext recordNext, DuelRecordBegin recordBegin, DuelIsRecordEnd isRecordEnd);
typedef int32_t (*DuelIsReplayModeType)(void);
typedef void (*SetDuelChallengeType)(int32_t flagbit);
typedef void (*SetDuelChallenge2Type)(int32_t player, int32_t flagbit);
typedef int32_t (*DuelListIsMultiModeType)(void);
typedef void (*DuelListInitStringType)(void);
typedef int32_t (*DuelListGetSelectMaxType)(void);
typedef int32_t (*DuelListGetSelectMinType)(void);
typedef int32_t (*DuelListGetItemMaxType)(void);
typedef int32_t (*DuelListGetItemIDType)(int32_t index);
typedef int32_t (*DuelListGetItemUniqueIDType)(int32_t index);
typedef int32_t (*DuelListGetItemFromType)(int32_t index);
typedef int32_t (*DuelListGetItemMsgType)(int32_t index);
typedef int32_t (*DuelListGetItemAttributeType)(int32_t index);
typedef int32_t (*DuelListGetCardAttributeType)(int32_t iLookPlayer, int32_t wUniqueID);
typedef void (*DuelListSetIndexType)(int32_t index);
typedef void (*DuelListSetCardExDataType)(int32_t index, int32_t data);
typedef int32_t (*DuelListGetItemTargetUniqueIDType)(int32_t index);

#endif